name: Ryan Shippy
favicon: null
layout_spectrum: 0.46724
typography_spectrum: 0.54589
title: Ryan Shippy
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75005315-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b8e042'
    - '#96d4bb'
    - '#e1f1ed'
    - '#9ed249'
  brandStrength: 0.4375
  lightness: 0.5
  saturation: 0.3125
  rhythmicContrast: 0.30732812848873436
purpose: []
