name: Ryan Shippy
favicon: null
layout_spectrum: 0.46724
typography_spectrum: 0.54589
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b8e042'
    - '#96d4bb'
    - '#e1f1ed'
    - '#9ed249'
  brandStrength: 0.4375
  lightness: 0.6719398749992251
  saturation: 0.11809300584718585
  rhythmicContrast: 0.30732812848873436
purpose: []
